CREATE USER ${JOIN_DB_USER} WITH PASSWORD '${JOIN_DB_PASSWORD}';
CREATE DATABASE ${JOIN_DB} OWNER ${JOIN_DB_USER};

CREATE USER ${CODERR_DB_USER} WITH PASSWORD '${CODERR_DB_PASSWORD}';
CREATE DATABASE ${CODERR_DB} OWNER ${CODERR_DB_USER};

CREATE USER ${VIDEOFLIX_DB_USER} WITH PASSWORD '${VIDEOFLIX_DB_PASSWORD}';
CREATE DATABASE ${VIDEOFLIX_DB} OWNER ${VIDEOFLIX_DB_USER};